Repository Open-Code-Crafters/FitFlex, pull requests merged in 2024-10, with the labels that each got.

#19 Improved the spacing in homepage, and the Card Content's Spacing and Visibility #10
  src/components/PlansCard.jsx
  src/components/PlansCard2.jsx
  src/views/Home.jsx
Labels: level 1

#45 Doc Update
  README.md
  src/assets/ReadMeAssests/screenShorts/GSSoC-Ext.png
  src/assets/ReadMeAssests/screenShorts/Hacktoberfest.png
  src/assets/ReadMeAssests/screenShorts/Homepage.png
Labels: hacktoberfest-accepted, hacktoberfest

#44 new page added, healthtips
  src/App.css
  src/App.jsx
  src/assets/health/balanced-diet.jpg
  src/assets/health/exercise.jpg
  src/assets/health/mental-health.jpg
  src/assets/health/mix-up-routine.jpg
  src/assets/health/posture.jpg
  src/assets/health/rest-recovery.jpg
  src/assets/health/strength-training.jpg
  src/assets/health/warmup-cooldown.jpg
  src/components/Footer.jsx
  src/components/Navbar.jsx
  src/components/healthtips.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#51 Log In broken link from register page bug solved : Issue no #49
  package-lock.json
  package.json
  src/views/Register.jsx
Labels: bug, enhancement, gssoc-ext, hacktoberfest-accepted, level3, hacktoberfest

#73 Feature/google auth
  package-lock.json
  package.json
  src/App.jsx
  src/context/Firebase.jsx
  src/main.jsx
  src/views/Login.jsx
  src/views/Register.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2, new feature, hacktoberfest

#72 Improved navbar responsiveness
  src/components/Footer.jsx
  src/components/Navbar.jsx
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#84 Added Services Section for Personal Training, Nutrition Counseling, Online Training(#issue 63)
  src/App.jsx
  src/components/Navbar.jsx
  src/views/Services.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2, new feature, hacktoberfest

#123 Toggle Mode Implemeted
  src/App.jsx
  src/components/Navbar.jsx
  src/components/SuccessStories.jsx
  src/views/About.jsx
  src/views/Blog.jsx
  src/views/Home.jsx
  src/views/Plans.jsx
  src/views/Services.jsx
  src/views/Workout.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3, new feature, hacktoberfest

#135 Implement Newsletter Subscription Feature Using Firebase
  src/components/Footer.jsx
  src/components/Subscribe.jsx
  src/context/Firebase.jsx
Labels: bug, gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#132 Added the Dockerfile
  Dockerfile
  README.md
  package-lock.json
  package.json
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#156 Addition Of ChatBot | Issue #37
  package-lock.json
  package.json
  src/App.jsx
  src/assets/img/robot.png
  src/components/BacktoTop.jsx
  src/components/ChatBot.jsx
  src/styles/BacktoTop.css
Labels: gssoc-ext, hacktoberfest-accepted, level3, new feature, hacktoberfest

#169 Local Storage Addition for User Data Storing and ChatBot Responsiveness | Issue #165
  src/components/FItFlexChatBot.jsx
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#239 Fix: Images in /plans route rendering now
  src/assets/health/water-hydration.jpg
  src/components/FItFlexChatBot.jsx
  src/components/PlansCard.jsx
  src/components/PlansCard2.jsx
  src/components/healthtips.jsx
  src/data/plans.json
  src/views/About.jsx
  src/views/Plans.jsx
  src/views/Services.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#270 Fixes #263: Width of pages for mobile view
  src/App.css
Labels: bug, gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#310 Update README.md with stats !!!
  README.md
Labels: documentation, gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#365 Updated the about section misalignment
  src/styles/about.css
  src/views/About.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#329 Enhance the Blogs Page | Issue #233
  src/styles/blog.css
  src/styles/blogs.css
  src/views/Blog.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#361 fixed faq issue
  src/components/FAQ.jsx
  src/components/Footer.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest
